// export const sampleImage = require("./Rectangle-1241-1.jpg.png")
export const bgimg1 = require("./bn2-2.jpg.png")
export const bgimg2 = require("./bn2-3.jpg.png")
export const bgimg3 = require("./bn2-4.jpg.png")
export const bgimg4 = require("./bn2-5.jpg.png")

export const latestimg1 = require("./blog1-450x580.jpg.png")
export const latestimg2 = require("./blog2-450x580.jpg.png")
export const latestimg3 = require("./blog3-450x580.jpg.png")
export const latestimg4 = require("./blog1-450x580.jpg.png")
export const latestimg5 = require("./blog2-450x580.jpg.png")
export const latestimg6 = require("./blog3-450x580.jpg.png")
export const latestimg7 = require("./blog1-450x580.jpg.png")
export const latestimg8 = require("./blog2-450x580.jpg.png")
export const contentimg1 = require("./contentimg1.png")
export const contentimg2 = require("./contentimg2.png")
export const contentimg3 = require("./contentimg3.png")

export const infoimg1 = require('./infoimg1.png')
export const infoimg2 = require('./infoimg2.png')
export const infoimg3 = require('./infoimg3.png')
export const infoimg4 = require('./infoimg4.png')
export const infoimg5 = require('./infoimg5.png')
export const infoimg6 = require('./infoimg6.png')

export const elbirth = require('./elbrit.png')
export const phoneimage = require('./phoneimg.png')
export const locationimage = require('./locationimg.png')
export const emailimage = require('./emailimg.png')
